### ISSUE TITLE
Cannot configure the plugin

### ISSUE THREAD

**Issue by nicolescalessa** [DBinaghi/plugin-CollectionsPlus#1]
I am running Omeka 3.1.1 (however I first tried in 3.1 before updating in hopes the situation would change) and when I click on configure I get a blank page. [](url)
![Screen Shot 2023-09-14 at 3 39 02 PM](https://github.com/DBinaghi/plugin-CollectionsPlus/assets/52713023/44b0dfeb-7c4a-460c-b515-1fff2221679d)
![Screen Shot 2023-09-14 at 3 39 15 PM](https://github.com/DBinaghi/plugin-CollectionsPlus/assets/52713023/471920bc-82db-4d25-b260-c2ab1fb9a6a8)

I was hoping to use this plugin to force the items in collections to sort by title instead of date added.

**Comment by DBinaghi** [comment]
Plugin version 1.1 seems to be working fine on Omeka 3.1 (I still have not got a chance to install the newest version), so I'm wondering whether something went wrong during your installation. Could you try uninstalling and then reinstalling the plugin? And are you facing any issue with any other of the plugins you've installed?
And, in `/admin/collections`, can you see the link to advanced settings for each Collection? What happens if you click on it?

**Comment by nicolescalessa** [comment]
I installed it first on Omeka 3.1 and it did not work. I uninstalled the plugin then deleted the files from the server. Then I updated Omeka to 3.1.1 and installed the plugin again. That is when I contacted support. Today I uninstalled it again, deleted the plugin files from the server, went to Omeka and downloaded a brand new file and installed that. Still nothing appearing on the Configuration page.

**Comment by nicolescalessa** [comment]
All other plugins are working fine. admin > themes > default > collections there is no advanced settings option. Also there was no "collections" directory immediately inside "admin" as you noted.

**Comment by DBinaghi** [comment]
Could you show me a screenshot of the `admin/collections` page? The one you reach by clicking on "collections" link in the admin side menu.

Also: I've noticed you have several plugins installed. There should not be any problem with that, but could you please try disabling all plugins but for the **CollectionsPlus** one and see whether it works?

**Comment by DBinaghi** [comment]
Try the just released version 1.2 and let me know if it fix your issue.

**Comment by nicolescalessa** [comment]
I installed the new version and it allows me to configure it now.

I set it to sort by date ascending (see screen shot). I do not see any
change on the back end or the front end for this collection:

See: https://roseman.vassarspaces.net/collections/show/284

If you scroll down, 2023-01-01 is still in the middle of the page
indicating that it is still sorting by when the records were created.

I need the records/photos to actually sort by the dublin core DATE field.

What am I doing wrong?

[image: Screen Shot 2023-09-19 at 6.41.35 PM.png]

Thanks,
Nicole

**Comment by DBinaghi** [comment]
Hi. I cannot see any screenshot. Could you try to reupload it? (you could edit the previous message, if so you wanted)

Also: plugin works fine for me, could it be you're chosing the Date Added or another Date field instead of the DC Date? Could you show me a screenshot of your plugin config page too?

**Comment by nicolescalessa** [comment]
![Screen Shot 2023-09-19 at 6 41 35 PM](https://github.com/DBinaghi/plugin-CollectionsPlus/assets/52713023/fba1cc72-3fcc-4325-931b-cd110b85fe53)

**Comment by DBinaghi** [comment]
Hi.
As said, the plugin seems to be working fine on my test archive.

So, I've checked the page you referred to, and I've noticed some inconsistencies and errors in the data published (examples: "Self-Portrait with Cathy Catherine Murphy)", or some Items totally missing the date), so I wonder whether the problems you're experiencing are caused by maybe typos in the date field (an O instead of a 0, and so on). I suggest you check all Items and then try to order them again.

Another attempt you could try would be to temporarily use an empty field (maybe "reference"), add some data (like a sequence of numbers: 1, 2, 3...) and then ask the plugin to sort Items by that field (ASC o DESC order) and see whether it works as expected.

Let me know results, thx.

**Comment by nicolescalessa** [comment]
So, yes I know we are missing data in the date field and because of this I
added dates to everything in this collection as a test:
https://roseman.vassarspaces.net/collections/show/284

This morning I changed the sorting to Dublin Core title, hard refreshed the
browser, no change. Changed it back to sort descending by Dublin Core Date,
hard refreshed again and still no change. I am using the Chrome browser.

I plan to have a student add a normalized date in the Dublin Core date
field based on the dates the emeriti faculty member used in the title
field. However, I am holding off assigning this project until I know the
plugin will work.

Thanks,
Nicole

**Comment by DBinaghi** [comment]
Ok, I probably found out what was the issue: we were talking about two different pages...

The plugin works on the way the Items of a Collection are shown, so the correct URL for that page should be https://roseman.vassarspaces.net/items/browse?collection=284 (in the case of your collection); if you check the page, you'll see that the sorting works as expected. One would get to that page by clicking on Items in the Self-Portraits 2023 Collection (40/42) at the top of the page.

What you were referencing to, is the preview of a Collection, that shows a limited number of Items; the plugin at the moment does not change the order of Items in that page. It might, in a future release, but not just now, so that's why you did see no change there.

Can you double check and confirm?

**Comment by nicolescalessa** [comment]
If I go to https://roseman.vassarspaces.net/items/browse?collection=284

the order is not by date, scroll down to May and it is 5/19/2023,
5/27/2023, 5/09/2023 etc.

I think I'll just have to manually put the dates in the front of the titles
and have users sort by title (already built into the site without the
plugin).

Thanks for your help. It's a shame this didn't work, it had a lot of
potential to help us out.

Nicole

**Comment by DBinaghi** [comment]
I keep thinking there must be some inconsistencies in your data, behaviour of the page is weird even without the plugin. 

Take, for instance, https://roseman.vassarspaces.net/items/browse?collection=284&sort_field=Dublin+Core%2CTitle&sort_dir=d, where you should have Items sorted by Title, ascending; well, I see displayed the sequence
_Self-Portrait at the Pamela Salisbury Gallery, Hudson, NYSeptember 21, 2023 Thursday_
_Self-Portrait with Olivier Mikhailoff. April 13, 2023 Thursday_
_Self-Portrait April 23, 2023 SundayWith swollen face_
that does not really make sense; again, I suggest that you use an unused field to add some sequence values for a few Items, then try to use the plugin with that field and see whether the sorting is correct; if it is, then the problem is the data already inserted, not the plugin itself.

Let me know if it works.

**Comment by nicolescalessa** [comment]
That's very likely. The faculty member that created the data content was
very inconsistent. That is why I tried to normalize the date field for that
one 2023 self-portrait collection but it still didn't work.

Thanks,
Nicole

**Comment by DBinaghi** [comment]
I've added the sorting to the `collections/show` (a.k.a. "landing") page, so that should cover your case (provided the data were consistent); the version is 1.3
Let me know if the tests I suggested worked out.

**Comment by nicolescalessa** [comment]
Wow, awesome. Thanks! I'll be in touch.

**Comment by nicolescalessa** [comment]
YAY!! It's working!!

https://roseman.vassarspaces.net/collections/show/284

Thank you so much!

Best,
Nicole

**Comment by DBinaghi** [comment]
I'm glad to hear that.
