### ISSUE TITLE
Random records are out of order when sort is set to DATE

### ISSUE THREAD

**Issue by nicolescalessa** [DBinaghi/plugin-CollectionsPlus#2]
I cannot figure out why the first item on this page dated 2009-04-11 is first and the others are in descending order. I tried to switch to ascending order to see if it would move and nothing happened (none of the dates changed order). I changed the date and it still did not move. What would make this sticky? It is not a featured item, the record looks like all the others in edit view. 

https://roseman.vassarspaces.net/collections/show/76

![Screenshot 2024-04-18 at 10 36 25 AM](https://github.com/DBinaghi/plugin-CollectionsPlus/assets/52713023/a14d43d6-9b5d-40c7-ae03-acc44c6a15da)

**Comment by DBinaghi** [comment]
Hi. 
First item: **HARRY ROSEMAN** 2009-04-11. Second item: **ROSEMAN, HARRY** 2009-01-06. Third item: **ROSEMAN, HARRY** 2009-01-09 etc.
Fix that consinstency problem, and let me know if the issue is solved.

**Comment by nicolescalessa** [comment]
That did not change anything.
https://roseman.vassarspaces.net/collections/show/76

Also, shouldn't the date field supersede the creator field for order if
that is what the plugin is set to?

**Comment by DBinaghi** [comment]
> Also, shouldn't the date field supersede the creator field for order if that is what the plugin is set to?

The image you attached to the first post refers to the field **all** Collections are to be sorted by (in the Collections Browse page), while you're asking a question about the Items inside a specific Collection (as per your link). You might want to check what's the Items sorting order for the Collection "Visitors 2009", maybe that will explain why that Item comes first (it could be just some extra characters in one of the fields).

**Comment by nicolescalessa** [comment]
Even if it is for all collections I would think the record would be in
order. How would I check the order for an individual collection? The plugin
isn't that granular.

**Comment by DBinaghi** [comment]
> The plugin isn't that granular

Quoting from the ReadMe.MD description, here:
_Plugin for Omeka Classic. Adds new features to the Collection browsing admin interface, and also the possibility to **further customize single Collections**.
Among other things, the plugin allows to:
choose a custom theme for each Collection;
choose a custom number of Items to be shown per page when browsing a Collection;
**choose a custom sort field and order for Items** when browsing a Collection and when seeing a Collection preview;
choose a custom sort field and order when browsing Collections._

If you go to your admin side, and choose Collections, you'll notice an **Advanced Settings** link under each Collection name; Items Sort Field and Items Sort Direction should be what you're looking for. But I would also check the fields of that particular Item, because again I believe something is written in way that is slighlty different from the other Items, and that's what's messing up with your sorting.

**Comment by nicolescalessa** [comment]
Thank you so much! I had no idea. I was looking under plugins. That worked.

Best,
Nicole

**Comment by DBinaghi** [comment]
Glad it worked. I'll update the instructions file.
